local wk = require("which-key")

wk.setup({
	preset = "helix",
	show_help = false,
	win = {
		border = "single",
	},
	icons = {
		breadcrumb = "",
		separator = "",
		group = "",
		ellipsis = "...",
		mappings = false,
		colors = false,
		keys = {
			Up = "Up",
			Down = "Down",
			Left = "Left",
			Right = "Rignt",
			C = "C-",
			M = "A-",
			D = "0-",
			S = "S-",
			CR = "CR",
			Esc = "Esc",
			ScrollWheelDown = "WheelDown",
			ScrollWheelUp = "WheelUp",
			NL = "NL",
			BS = "BS",
			Space = "space",
			Tab = "Tab",
			F1 = "F1",
			F2 = "F2",
			F3 = "F3",
			F4 = "F4",
			F5 = "F5",
			F6 = "F6",
			F7 = "F7",
			F8 = "F8",
			F9 = "F9",
			F10 = "F10",
			F11 = "F11",
			F12 = "F12",
		},
	},
})

wk.add({
	{ "g", group = "Global" },
	{ "<c-w>", group = "Window" },
	{ "<leader>", group = "Space" },
	{ "<leader>g", group = "Goto" },
	{ "[", group = "Left bracket" },
	{ "]", group = "Right bracket" },
})
